
package com.wipro.ws.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimpleSOAPServiceImplService", targetNamespace = "http://client.ws.wipro.com/", wsdlLocation = "http://localhost:1235/MySOAPService?wsdl")
public class SimpleSOAPServiceImplService
    extends Service
{

    private final static URL SIMPLESOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMPLESOAPSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SIMPLESOAPSERVICEIMPLSERVICE_QNAME = new QName("http://client.ws.wipro.com/", "SimpleSOAPServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1235/MySOAPService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMPLESOAPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SIMPLESOAPSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SimpleSOAPServiceImplService() {
        super(__getWsdlLocation(), SIMPLESOAPSERVICEIMPLSERVICE_QNAME);
    }

    public SimpleSOAPServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMPLESOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public SimpleSOAPServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SIMPLESOAPSERVICEIMPLSERVICE_QNAME);
    }

    public SimpleSOAPServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMPLESOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public SimpleSOAPServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleSOAPServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimpleSOAPServiceImpl
     */
    @WebEndpoint(name = "SimpleSOAPServiceImplPort")
    public SimpleSOAPServiceImpl getSimpleSOAPServiceImplPort() {
        return super.getPort(new QName("http://client.ws.wipro.com/", "SimpleSOAPServiceImplPort"), SimpleSOAPServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleSOAPServiceImpl
     */
    @WebEndpoint(name = "SimpleSOAPServiceImplPort")
    public SimpleSOAPServiceImpl getSimpleSOAPServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://client.ws.wipro.com/", "SimpleSOAPServiceImplPort"), SimpleSOAPServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMPLESOAPSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SIMPLESOAPSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SIMPLESOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
